# Generated by Django 5.2.8 on 2025-12-01 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ("-created_date",)},
        ),
    ]
