# Generated by Django 5.2.8 on 2025-12-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, default="blog/default.jpg", null=True, upload_to="blog/"
            ),
        ),
    ]
