# Generated by Django 5.2.8 on 2025-12-20 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_date"]},
        ),
    ]
